---
# tasks file for apache2
- name: install apache2
  apt: name={{item}} state=present update_cache=true
  become: true
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - python-pip
    - python-virtualenv
    - python-mysqldb
    - python3-pymysql
- name: start apache2
  service: name=apache2 state=started enabled=yes
  become: true
- name: enable apache2 WSGI module
  apache2_module: name=wsgi state=present
  notify: restart apache2
  become: true
