---
- hosts: loadbalancer
  become: true
  tasks:
   - name: stop load balancer
     service: name=nginx state=stopped
- hosts: webserver
  become: true
  tasks:
   - name: stop webserver
     service: name=apache2 state=stopped
- hosts: database
  become: true
  tasks: 
   - name: restart database
     service: name=mysql state=restarted
- hosts: webserver
  become: true
  tasks:
   - name: start webserver
     service: name=apache2 state=started
- hosts: loadbalancer
  become: true
  tasks:
   - name: start load balancer
     service: name=nginx state=started
